import { Worker, Job } from "bullmq";
import { redisConnection } from "../config/redis";
import { ResearchJobData, ResearchJobResult, AgentProgress } from "../types";
import logger from "../utils/logger";

const sleep = (ms: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, ms));


const runAgent = async (
  job: Job<ResearchJobData>,
  agent: AgentProgress["agent"],
  label: string,
  task: () => Promise<string>
): Promise<string> => {
  await job.updateProgress({ agent, status: "active" } as AgentProgress);
  logger.info(`Agent started`, { jobId: job.id, agent: label });

  const result = await task();

  await job.updateProgress({ agent, status: "completed" } as AgentProgress);
  logger.info(`Agent completed`, { jobId: job.id, agent: label });

  return result;
};


const researchWorker = new Worker<ResearchJobData, ResearchJobResult>(
  "research",
  async (job: Job<ResearchJobData>): Promise<ResearchJobResult> => {
    const { topic, userId } = job.data;
    logger.info(`Research job started`, { jobId: job.id, topic });

    const searchResults = await runAgent(
      job, "searcher", "Web Searcher",
      async () => {
        await sleep(2000);

        return `Search results for "${topic}": 10 relevant sources found.`;
      }
    );

    const summary = await runAgent(
      job, "summarizer", "Summarizer",
      async () => {
        await sleep(2000);

        return `Summary of key findings about "${topic}".`;
      }
    );

    const verifiedSummary = await runAgent(
      job, "factChecker", "Fact Checker",
      async () => {
        await sleep(2000);

        return `All claims about "${topic}" verified.`;
      }
    );

    const report = await runAgent(
      job, "writer", "Report Writer",
      async () => {
        await sleep(2000);

        return [
          `# Research Report: ${topic}`,
          `## Search Findings`,  searchResults,
          `## Summary`,          summary,
          `## Verified Facts`,   verifiedSummary,
          `## Conclusion`,
          `Auto-generated by AI Research Agent.`,
        ].join("\n\n");
      }
    );

    logger.info(`Research job completed`, { jobId: job.id, topic });
    return { topic, userId, report };
  },
  {
    connection: redisConnection,
    concurrency: 3,
  }
);


researchWorker.on("completed", (job: Job, result: ResearchJobResult) => {
  logger.info(`Job completed`, { jobId: job.id, topic: result.topic });
});

researchWorker.on("failed", (job: Job | undefined, err: Error) => {
  logger.error(`Job failed`, { jobId: job?.id, error: err.message });
});

researchWorker.on("progress", (_job: Job, progress) => {
  const typedProgress = progress as AgentProgress;
  logger.info(`Agent progress`, { agent: typedProgress.agent, status: typedProgress.status });
});

export default researchWorker;